var minimap = [
    {
        SPX : 0,
        SPY : -250,
        SPZ : 250,
        angX : 0,
        angY : 0,
        angZ : 0,
        length : 1000,
        width : 10,
        height : 500,
        class_top : 'wall_style',
        class_bot : 'wall_style',
        class_front : 'wall_style',
        class_back : 'wall_style',
        class_sideleft : 'wall_style',
        class_sideright : 'wall_style'
    },
    {
        SPX : 150,
        SPY : -250,
        SPZ : 350,
        angX : 0,
        angY : 0,
        angZ : 0,
        length : 800,
        width : 10,
        height : 500,
        class_top : 'wall_style',
        class_bot : 'wall_style',
        class_front : 'wall_style',
        class_back : 'wall_style',
        class_sideleft : 'wall_style',
        class_sideright : 'wall_style'
    },
    {
       SPX : 0,
       SPY : -250,
       SPZ : -255,
       angX : 0,
       angY : 0,
       angZ : 0,
       length : 10,
       width : 400,
       height : 500,
       class_top : 'wall_style',
       class_bot : 'wall_style',
       class_front : 'wall_style',
       class_back : 'wall_style',
       class_sideleft : 'wall_style',
       class_sideright : 'wall_style'
    },
    {
       SPX : 400,
       SPY : -250,
       SPZ : 140,
       angX : 0,
       angY : 0,
       angZ : 0,
       length : 800,
       width : 10,
       height : 500,
       class_top : 'wall_style',
       class_bot : 'wall_style',
       class_front : 'wall_style',
       class_back : 'wall_style',
       class_sideleft : 'wall_style',
       class_sideright : 'wall_style'
    },
    {
       SPX : 150,
       SPY : -250,
       SPZ : 750,
       angX : 0,
       angY : 0,
       angZ : 0,
       length : 10,
       width : 800,
       height : 500,
       class_top : 'wall_style',
       class_bot : 'wall_style',
       class_front : 'wall_style',
       class_back : 'wall_style',
       class_sideleft : 'wall_style',
       class_sideright : 'wall_style'
    },
    {
        SPX : 0,
        SPY : 251,
        SPZ : 0,
        angX : 0,
        angY : 0,
        angZ : 0,
        length : 1500,
        width : 1500,
        height : 1,
        class_top : 'grass_style',
        class_bot : 'grass_style',
        class_front : 'grass_style',
        class_back : 'grass_style',
        class_sideleft : 'grass_style',
        class_sideright : 'grass_style'
    },
    //{
    //    SPX : 0,
    //    SPY : 0,
    //    SPZ : 100,
    //    angX : 0,
    //    angY : 0,
    //    angZ : 0,
    //    length : 250,
    //    width : 10,
    //    height : 200,
    //    class_top : 'wall_style',
    //    class_bot : 'wall_style',
    //    class_front : 'wall_style',
    //    class_back : 'wall_style',
    //    class_sideleft : 'wall_style',
    //    class_sideright : 'wall_style'
    //},
    //{
    //    SPX : 0,
    //    SPY : 0,
    //    SPZ : -20,
    //    angX : 0,
    //    angY : 0,
    //    angZ : 0,
    //    length : 10,
    //    width : 340,
    //    height : 200,
    //    class_top : 'wall_style',
    //    class_bot : 'wall_style',
    //    class_front : 'wall_style',
    //    class_back : 'wall_style',
    //    class_sideleft : 'wall_style',
    //    class_sideright : 'wall_style'
    //},
    //{
    //    SPX : 340,
    //    SPY : 0,
    //    SPZ : 100,
    //    angX : 0,
    //    angY : 0,
    //    angZ : 0,
    //    length : 250,
    //    width : 10,
    //    height : 200,
    //    class_top : 'wall_style',
    //    class_bot : 'wall_style',
    //    class_front : 'wall_style',
    //    class_back : 'wall_style',
    //    class_sideleft : 'wall_style',
    //    class_sideright : 'wall_style'
    //},
    //{
    //    SPX : '',
    //    SPY : '',
    //    SPZ : '',
    //    angX : '',
    //    angY : '',
    //    angZ : '',
    //    length : '',
    //    width : '',
    //    height : '',
    //    class_top : '',
    //    class_bot : '',
    //    class_front : '',
    //    class_back : '',
    //    class_sideleft : '',
    //    class_sideright : ''
    //},
    //{
    //    SPX : '',
    //    SPY : '',
    //    SPZ : '',
    //    angX : '',
    //    angY : '',
    //    angZ : '',
    //    length : '',
    //    width : '',
    //    height : '',
    //    class_top : '',
    //    class_bot : '',
    //    class_front : '',
    //    class_back : '',
    //    class_sideleft : '',
    //    class_sideright : ''
    //}
];